// PROJECT EULER: PROBLEM TWO
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

// SOLUTION
// STEP ONE: Create your sum value to increment all even pair combinations in the sequence, create previous and current values also to represent the pairs in the Fibonacci sequence
// STEP TWO: Create while loop that checks if the combination of previous and current exceed 4000000
// STEP THREE: We create conditonal term in our loop that checks if our sum of the sequence pairs is divisible by 2 (Even) then we add it to our total, else we add 0 to the total sum



let sum = 0;
let previous = 0;
let current = 1;


while (current < 4000000) {
current = previous + current;
previous = current - previous;
sum += current % 2 === 0 ? current : 0;

}
console.log(sum);